apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
secretGenerator:
- envs:
  - waldur-api-secret.env
  name: waldur-api-secret
  options:
    disableNameSuffixHash: true
configMapGenerator:
- envs:
  - waldur-controller-config.env
  name: waldur-controller-config
  options:
    disableNameSuffixHash: true
images:
- name: controller
  newName: ghcr.io/waldur/cluster-api-provider-waldur
  newTag: v0.1.0
