---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.cluster.waldur.com
  resources:
  - waldurclusters
  - waldurmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.waldur.com
  resources:
  - waldurclusters/finalizers
  - waldurmachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.waldur.com
  resources:
  - waldurclusters/status
  - waldurmachines/status
  verbs:
  - get
  - patch
  - update
