apiVersion: infrastructure.cluster.waldur.com/v1beta1
kind: WaldurCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-waldur
    app.kubernetes.io/managed-by: kustomize
  name: waldurcluster-sample
spec:
  # TODO(user): Add fields here
