apiVersion: infrastructure.cluster.waldur.com/v1beta1
kind: WaldurMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-waldur
    app.kubernetes.io/managed-by: kustomize
  name: waldurmachine-sample
spec:
  # TODO(user): Add fields here
